booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from bookingvisit import views
app_name ='test1_app'

urlpatterns = [
    path("authorisathion/", include('django.contrib.auth.urls')),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('', views.IndexView.as_view(), name='index'),
    path('salon-login/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('profil/<int:pk>/', views.ClientProfilView.as_view(), name='profil'),
    path('update-name/<int:pk>/', views.UserNameUpdateView.as_view(), name='name_update'),
    path('update/<int:pk>/', views.UserEmailUpdateView.as_view(), name='email_update'),
    path('update/<int:pk>/phone', views.UpdateClientProfilView.as_view(), name='number_update'),
    path('profil/reservation-hairdresser/<int:pk>/', views.ReservationHairdersesrView.as_view(), name='client_reservation_hairdresser'),
    path('profil/<int:pk>/reservation-beautician/', views.ReservationBeauticianView.as_view(), name='client_reservation_beautician'),
    path('profil/reservation/<int:pk>/', views.ReservationListView.as_view(), name='client_reservation_list'),
    path('opinion/', views.OpinionsListView.as_view(), name='opinions'),
    path('profil/opinion/<int:pk>', views.ClientOpinionListView.as_view(), name='client_opinion'),
    path('profil/<int:pk>/create-opinion/', views.ClientOpinonView.as_view(), name='create_client_opinion'),
    path('profil/opinion/<int:pk>/update/', views.ClientOpinonUpdateView.as_view(), name='client_opinion_update'),
    path('profil/opinion/<int:pk>/delete/', views.ClientOpinonDeleteView.as_view(), name='client_opinion_delete'),


]

bookingvisit/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User



class HServices(models.Model):
    service = models.CharField(max_length=128)
    time_service = models.IntegerField()
    price_service = models.IntegerField()

    def __str__(self):
        return self.service

    class Meta:
        verbose_name_plural = '3 Usługi fryzjerskie'

class Hairdresser(models.Model):
    name = models.CharField(max_length=64)
    surname = models.CharField(max_length=64)
    services = models.ManyToManyField(HServices)
    workplace_number = models.IntegerField()

    def __str__(self):
        return f'{self.name} {self.surname}'

    class Meta:
        verbose_name_plural = '1 Fryzjerzy'
        verbose_name = 'Fryzjera'

class BServices(models.Model):
    service = models.CharField(max_length=128)
    time_service = models.IntegerField()
    price_service = models.IntegerField()

    def __str__(self):
        return self.service

    class Meta:
        verbose_name_plural = '4 Usługi kosmetyczne'

class Beautician(models.Model):
    name = models.CharField(max_length=32)
    surname = models.CharField(max_length=64)
    services = models.ManyToManyField(BServices)
    workplace_number = models.IntegerField()

    def __str__(self):
        return f'{self.name} {self.surname}'

    class Meta:
        verbose_name_plural = '2 Kosmetyczki'

class Client_Profil(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='profile')
    phone_number = models.CharField(max_length=12, default='brak numeru')

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} {self.user.email} {self.phone_number}'

    class Meta:
        def __str__(self):
            return f'{self.user.username} Profil'
        verbose_name_plural = '5 Użytkownicy'


class Reservation_Hairdresser(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    employees = models.ForeignKey(Hairdresser, on_delete=models.CASCADE, verbose_name='Pracownik')
    services = models.ForeignKey(HServices, on_delete=models.CASCADE, verbose_name='Usługa')
    day = models.DateField(default=datetime.date.today, verbose_name='Data')
    start_time = models.TimeField(default='08:00', verbose_name='Godzina')

    def __str__(self):
        return f'{self.day} {self.start_time}'

    class Meta:
        verbose_name_plural = '6 Rezerwacje do fryzjera'

class Reservation_Beautician(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    employees = models.ForeignKey(Beautician, on_delete=models.CASCADE, verbose_name='Pracownik')
    services = models.ForeignKey(BServices, on_delete=models.CASCADE, verbose_name='Usługa')
    day = models.DateField(default=datetime.date.today, verbose_name='Data')
    start_time = models.TimeField(default='09:00', verbose_name='Godzina')

    def __str__(self):
        return f'{self.day} {self.start_time}'

    class Meta:
        verbose_name_plural = '7 Rezerwacje do kosmetyczki'

class Opinions(models.Model):
    objects = None
    rating = models.IntegerField(default=round(5))
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    opinion = models.TextField()
    data = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.data}'

    class Meta:
        verbose_name_plural = '8 Opinie'

templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="content">
    {% block content %}
    {% endblock %}
</div>
<div class="navigation">
    {% include 'buttons.html' %}
{% if user.is_authenticated %}
<br><br>
    <hr>
    <br><br><br><center><p><h1>Miło cię widzieć {{ user.first_name }}!</h1></p>
            <br><br><br>
    <hr>
        <p><a href="{% url 'profil' pk=user.id %}">Mój profil</a> </p>
    <hr>
        <p><a href="{% url 'client_reservation_hairdresser' pk=user.id %}">Rezerwacja wizyty u fryzjera</a> </p>
    <hr>
        <p><a href="{% url 'client_reservation_beautician' pk=user.id %}">Rezerwacja wizyty u kosmetyczki</a> </p>
    <hr>
        <p><a href="{% url 'client_reservation_list' pk=user.pk %}">Moje wizyty</a> </p>
    <hr>
    <p><a href="{% url 'client_opinion' pk=user.pk %}">Moje opinie</a> </p></center>
    <hr>
{% endif %}

</div>


</body>


</html>

templates/buttons.html
{% if user.is_authenticated %}

    <center><a href="{% url 'index' %}">Home</a> <a href="{% url 'logout' %}">Wyloguj się</a></center>

{% else %}


			<br><br><center><h1>"Easybooking"</h1></center>
			<center><h2>Twój ulubiony fryzjer!</h2></center><br>
<center><button><a href="{% url 'login' %}"><h2><b>UMÓW WIZYTĘ</b></h2></a></button></center>
			<br><center><h3>Umów wizytę w szybki i prosty sposów!</h3></center>
	<br>
	<br>
	<hr>
        <center><p><a href="{% url 'opinions' %}">Wasze opinie</a> </p></center>
    <hr>
{% endif %}

templates/client_delete_opinion.html
{% extends 'base.html' %}

{% block content %}
    <h2>Czy jestes pewien, że chcesz usunąć opinie {{ object }}?</h2>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="TAK">
    </form>
{% endblock  %}

templates/client_opinion.html
<div class="navigation">
  {% include 'buttons.html' %}</div>
{% if user.is_authenticated %}
  <h2>Twoja opinie</h2>
  {% if opinion_list %}

    {% for o in opinion_list %}

    <ul id="menu">
      <br><li><b> Ocena: {{ o.rating }}</b></li>
      <br> {{ o.opinion }}
      <p class="text-muted mb-0" style="font-size: 8px">Wystawione przez: {{ o.client }} | Data wystawienia: {{ o.data }}</p>

    </ul>

    {% endfor %}

    <br><a href="{% url 'client_opinion_update' pk=user.pk %}"><b>Edytuj opinie</b></a>
    <br><a href="{% url 'client_opinion_delete' pk=user.pk %}"><b>Usuń opinie</b></a>

  {% else %}

    <p>Brak opini.</p>
    <br><a href="{% url 'create_client_opinion' pk=user.pk %}"><b>Wystaw opinie</b></a>


  {% endif %}


{%endif %}
<hr>
  <br>
    <center><button class="button"><a href="{% url 'index' %}"><b>Wstecz</b></a></button></center>

templates/client_profil.html
 {% include 'buttons.html' %}

{% if user.is_authenticated %}

<html lang="pl">

    <center><p class="text-muted mb-0" style="font-size: 8px">Ostatnio zalogowany: {{ user.last_login }}</p>
<button class="button"><a href="{% url 'index' %}">Wstecz</a> </button></center>



    <center> <br><div class="container mx-auto"></center>
    <div class="center-block">
        <div class="col-sm-12 col-md-12 col-lg-3 pb-4">
            <div class="card p-7">
                <h4 class="card-title font-weight-bold text-center">Twój profil {{ user.first_name|title }}</h4>
                <hr>
                <div class="card-text">
                    <center><p class="text-muted mb-0" style="font-size: 12px">Username:</p></center>
                    <center><p>{{ user.username }}</p>
                    <p class="text-muted mb-0" style="font-size: 12px">Name:</p>
                    <p>{{ user.first_name }} {{ user.last_name }} <br><button class="button"><a href="{% url 'name_update' pk=user.id %}">Edytuj</a> </button></p>
                    <p class="text-muted mb-0" style="font-size: 12px">Email:</p>
                    <p>{{ user.email }}<br><button class="button"><a href="{% url 'email_update' pk=user.id %}">Edytuj</a></button></p>
                    <p class="text-muted mb-0" style="font-size: 12px">Telefon:</p>
                    <p>{{ object.phone_number }}<br><button class="button"><a href="{% url 'number_update' pk=object.id %}">Edytuj</a></button></p>
                    <p class="text-muted mb-0" style="font-size: 12px">Konto utworzone:</p>
                    <p>{{ user.date_joined }}</p></center>
                </div>
            </div>
        </div>
    </div>
</div>
<center>
<button class="button"><a href="{% url 'password_change' %}">Zmień hasło</a> </button>
<button class="button"><a href="{% url 'password_reset' %}">Zresetuj hasło</a> </button>
</center>

<br><br>

{% else %}
{% endif %}


</main>
</body>
</html>

templates/client_reservation.html
<div class="navigation">
    {% include 'buttons.html' %}</div>

{% if user.is_authenticated %}
  <hr><br>
<center><button class="button"><a href="{% url 'index' %}">Wstecz</a> </button></center>
<br>
{% block content %}

    <br>
    <center>
        <form action="" enctype="multipart/form-data" method="post"  >
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" value="Umów wizytę">
    </form></central>
{% endblock %}
{#{% else %}#}
{#    <p><a href="{% url 'login' %}">Zaloguj się</a> </p>#}
{% endif %}

templates/client_reservation_list.html
<div class="navigation">
    {% include 'buttons.html' %}
</div>
<h2>Twoje rezerwacje u kosmetyczki</h2>

<ul id="menu">
  {% for b in rezervation_list %}

    <li><p>Imię kosmetyczki: {{ b.employees }} | Nazwa usługi: {{ b.services }} | Data: {{ b.day }} | Godzina: {{ b.start_time }} |</p></li>
        <p><b>| Czas usługi: {{ b.services.time_service }} minut | Koszt usługi: {{b.services.price_service}} zł |</b></p><br>
    {% endfor %}

</ul>
    <hr>
<h2>Twoje rezerwacje u fryzjera</h2>
    <ul id="menu1">
  {% for h in rezervation_list_2 %}

    <li><p>Imię Fryzjera: {{ h.employees }} | Nazwa usługi: {{ h.services }} | Data: {{ h.day }} | Godzina: {{ h.start_time }}</p></li>
        <p><b>| Czas usługi: {{ h.services.time_service }} minut | Koszt usługi: {{h.services.price_service}} zł |</b></p><br>
  {% endfor %}
    </ul>

<hr>
  <br>
    <center><button class="button"><a href="{% url 'index' %}"><b>Wstecz</b></a></button></center>

templates/client_update.html
<div class="navigation">
    {% include 'buttons.html' %}
{% if user.is_authenticated %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Uzupełnij dane">
    </form>
        <p><a href="{% url 'index' %}">Strona główna</a> </p>
        <p><a href="{% url 'logout' %}">Logout</a> </p>
{% endblock %}
{#{% else %}#}
{#    <p><a href="{% url 'login' %}">Login</a> </p>#}
{% endif %}

templates/opinion.html
<center><a href="{% url 'index' %}">Home</a> <a href="{% url 'login' %}">Zaloguj się</a></center>
<br>
<hr>
<br>
<center><button class="button"><a href="{% url 'index' %}">Wstecz</a> </button></center>
<hr>
<h2>Wasze opinie</h2>
  {% if opinions_list %}

    {% for o in opinions_list %}
    <hr>
    <ul id="menu">
      <br><li><b> Ocena: {{ o.rating }}</b></li>
      <br> {{ o.opinion }}
      <p class="text-muted mb-0" style="font-size: 8px">Wystawione przez: {{ o.client }} | Data wystawienia: {{ o.data }}</p>
    </ul>
    <hr>
    {% endfor %}

  {% else %}

    <p>BRAK OPINII</p>

  {% endif %}